version: "3"
services:
  app-container:
    ports:
      - "8080:80"
    depends_on:
      - react-app
      - ng-app
    build: .
  react-app:
    build:
      context: .
      dockerfile: ./packages/react-app/Dockerfile
  ng-app:
    build:
      context: .
      dockerfile: ./packages/ng-app/Dockerfile