name: Deploy to S3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Build React
      run: yarn && yarn build:react
    - name: Deploy React MFE to S3 bucket
      run: aws s3 sync ./packages/react-app/build/ s3://${{ AWS_REACT_BUCKET_NAME }} --delete
      - name: Build NG
      run: yarn && yarn build:NG
    - name: Deploy React MFE to S3 bucket
      run: aws s3 sync ./packages/ng-app/dist/ng-app/ s3://${{ AWS_NG_BUCKET_NAME }} --delete